  </title>

  <!-- Included CSS Files (Uncompressed) -->
  <!-- <link rel="stylesheet" href="stylesheets/foundation.css"> -->
  
  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="/opac-tmpl/foundation/stylesheets/app.css">
  <link rel="stylesheet" href="/opac-tmpl/foundation/stylesheets/koha.css">

  <!-- Included JS Files (Compressed) -->
  <script src="/opac-tmpl/foundation/javascripts/foundation/modernizr.foundation.js"></script>
